name: Login to AWS

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    # Assume role in Cloud Platform
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ vars.ECR_REGION }}

    # Login to container repository
    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
