name: Login to AWS

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Assume role in Cloud Platform
      uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6.1.0
      with:
        role-to-assume: ${{ env.ROLE }}
        aws-region: ${{ env.AWS_REGION }}
