name: Login to AWS

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Debug AWS_REGION
      run: echo "AWS_REGION=${{ env.AWS_REGION }}"

    - name: Assume role in Cloud Platform
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE }}
        aws-region: ${{ env.AWS_REGION }}
