name: Build and push docker image

environment: dev # Points to the set of environment secrets kept in GitHub secrets

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4

    # Build and push a Docker image to the container repository
    - run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ env.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ github.sha }}
      shell: bash