name: Checkout and build OpenAPI repository

outputs:
  version:
    description: 'Openapi version'
    value: ${{ steps.get_openapi_version.outputs.version }}

inputs:
  subfolder:
    description: 'Destination of code being used for build'

runs:
  using: 'composite'
  steps:

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Get openapi version from pom
      id: get_openapi_version
      run: |
        if [[ -n "${{ inputs.subfolder }} ]]; then 
          cd inputs.subfolder
          echo "I WENT INTO THE IF"
          pwd
        fi
        VERSION=$(mvn help:evaluate -Dexpression="payforlegalaid-openapi.version" -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell:
        bash

    - name: Checkout openapi spec
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-openapi
        path: openapi
        ref: refs/tags/v${{ steps.get_openapi_version.outputs.version }}

    - name: Build openapi spec dependency
      run: |
        cd openapi
        mvn -B clean install
      shell:
        bash
