name: Checkout and build OpenAPI repository

outputs:
  version:
    description: 'Openapi version'
    value: ${{ steps.get_openapi_version.outputs.version }}

inputs:
  subfolder:
    description: 'Location of code being used to define openapi version'

runs:
  using: 'composite'
  steps:

    - name: Setup Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'
        server-id: github-platform
        server-username: ${{ secrets.GITHUB_USERNAME }}
        server-password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get openapi version from pom
      id: get_openapi_version
      env:
        SUBFOLDER: ${{ inputs.subfolder }}
      run: |
        if [[ -n "$SUBFOLDER" ]]; then 
          cd "$SUBFOLDER"
        fi
        VERSION=$(mvn help:evaluate -Dexpression="payforlegalaid-openapi.version" -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell:
        bash

    - name: Checkout openapi spec
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      env:
        OPENAPI_VERSION: ${{ steps.get_openapi_version.outputs.version }}
      with:
        repository: ministryofjustice/payforlegalaid-openapi
        path: openapi
        ref: refs/tags/v${{ env.OPENAPI_VERSION }}

    - name: Build openapi spec dependency
      run: |
        cd openapi
        mvn -B -ntp clean install
      shell:
        bash
