name: Setup Maven

inputs:
  github-username:
    required: true
    description: 'GitHub username'
  github-token:
    required: true
    description: 'GitHub token'

runs:
  using: 'composite'

  steps:

    - name: Setup Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'

    - name: Configure Maven credentials
      shell: bash
      run: |
        mkdir -p ~/.m2

        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <profiles>
            <profile>
              <id>github</id>
              <repositories>
                <repository>
                  <id>github-openapi</id>
                  <url>https://maven.pkg.github.com/ministryofjustice/payforlegalaid-openapi</url>
                </repository>
                <repository>
                  <id>github-platform</id>
                  <url>https://maven.pkg.github.com/ministryofjustice/glad-platform</url>
                </repository>
              </repositories>
            </profile>
          </profiles>

          <activeProfiles>
            <activeProfile>github</activeProfile>
          </activeProfiles>

          <servers>
            <server>
              <id>github-openapi</id>
              <username>${{ inputs.github-username }}</username>
              <password>${{ inputs.github-token }}</password>
            </server>
            <server>
              <id>github-platform</id>
              <username>${{ inputs.github-username }}</username>
              <password>${{ inputs.github-token }}</password>
            </server>
          </servers>
        </settings>
        EOF