name: Checkout and build OpenAPI repository

outputs:
  version:
    description: 'Openapi version'
    value: ${{ steps.get_openapi_version.outputs.version }}

runs:
  using: 'composite'
  steps:

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    #        Define allowed properties to get openapi version safely
    #        Protects against Log4Shell attack
    - name: Get openapi version from pom
      id: get_openapi_version
      run: |
        case "${{ inputs.property-name }}" in
          "payforlegalaid-openapi.version"
            VERSION=$(mvn help:evaluate -Dexpression="${{ inputs.property-name }}" -q -DforceStdout)
            echo "version=$VERSION" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "Error: Unauthorized property name"
            exit 1
            ;;
        esac
      shell:
        bash

    - name: Checkout openapi spec
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-openapi
        path: openapi
        ref: refs/tags/v${{ steps.get_openapi_version.outputs.version }}

    - name: Build openapi spec dependency
      run: |
        cd openapi
        mvn -B clean install
      shell:
        bash
