name: Checkout and build OpenAPI repository

outputs:
  version:
    description: 'Openapi version'
    value: ${{ steps.get_openapi_version.outputs.version }}

inputs:
  subfolder:
    description: 'Location of code being used to define openapi version'
  github-username:
    required: true
    description: 'GitHub username'
  github-token:
    required: true
    description: 'GitHub token'

runs:
  using: 'composite'
  steps:

    - name: Setup Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'
        server-id: github-platform
        server-username: github-username
        server-password: github-token
      env:
        github-username: ${{ inputs.github-username }}
        github-token: ${{ inputs.github-token }}

    - name: Configure Maven credentials
      shell: bash
      run: |
        mkdir -p ~/.m2
        
        cat > ~/.m2/settings.xml <<EOF
        <settings>
          <servers>
            <server>
              <id>github-openapi</id>
              <username>${{ inputs.github-username }}</username>
              <password>${{ inputs.github-token }}</password>
            </server>
            <server>
              <id>github-platform</id>
              <username>${{ inputs.github-username }}</username>
              <password>${{ inputs.github-token }}</password>
            </server>
          </servers>
        </settings>
        EOF

    - name: Get openapi version from pom
      id: get_openapi_version
      env:
        SUBFOLDER: ${{ inputs.subfolder }}
      run: |
        echo "username=${{ inputs.github-username }}"
        echo "token supplied"
        if [[ -n "$SUBFOLDER" ]]; then 
          cd "$SUBFOLDER"
        fi
        VERSION=$(mvn help:evaluate -Dexpression="payforlegalaid-openapi.version" -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
      shell:
        bash

    - name: Checkout openapi spec
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      env:
        OPENAPI_VERSION: ${{ steps.get_openapi_version.outputs.version }}
      with:
        repository: ministryofjustice/payforlegalaid-openapi
        path: openapi
        ref: refs/tags/v${{ env.OPENAPI_VERSION }}

#    - name: Build openapi spec dependency
#      run: |
#        cd openapi
#        mvn -B -ntp clean install
#      shell:
#        bash
