name: Checkout and run tests

runs:
  using: 'composite'
  steps:
    # Checkout GitHub repository
    - name: checkout
      uses: actions/checkout@v4

    # Setup Javax
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    # Run Tests
    - name: Run tests
      shell: bash
      run: mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
