title = "gitleaks config"

[extend]
useDefault = true

[allowlist]
description = "Ignore UUIDs in test fixtures"

paths = [
    '''src/test/.*'''
]

regexes = [
    '''[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}'''
]