sonar.cpd.exclusions=src/main/resources/flyway/**
sonar.exclusions=src/main/resources/flyway/**
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.projectKey=ministryofjustice_payforlegalaid
sonar.organization=ministryofjustice
