name: Login to AWS

runs:
  using: 'composite'
  environment: uat # Points to the set of environment secrets kept in github secrets

  steps:
    - uses: actions/checkout@v4

    # Assume role in Cloud Platform
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ROLE }}
        aws-region: ${{ vars.ECR_REGION }}

    # Login to container repository
    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr
