name: Login to AWS

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Assume role in Cloud Platform
      uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd # v6.3.0
      with:
        role-to-assume: ${{ env.ROLE }}
        aws-region: ${{ env.AWS_REGION }}
