name: Login to AWS

runs:
  using: 'composite'

  steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Assume role in Cloud Platform
      uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
      with:
        role-to-assume: ${{ env.ROLE }}
        aws-region: ${{ env.AWS_REGION }}
