logging:
  level:
    root: DEBUG
    org.apache.coyote.http11.Http11Processor: WARN
    org.apache.tomcat.util.net.NioEndpoint: WARN
    org.apache.tomcat: WARN
    org.apache.coyote: WARN
    org:
      springframework:
        security: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
        transaction: INFO
        web: INFO

server:
  servlet:
    session:
      timeout: 0
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yml


spring:
  mvc:
    async:
      request-timeout: 3600000
