gpfd:
  redirect-uri-template: https://laa-get-payments-finance-data-dev.apps.live.cloud-platform.service.justice.gov.uk/login/oauth2/code/gpfd-azure-dev

spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${AZURE_TENANT_ID}
        credential:
          client-id: ${AZURE_CLIENT_ID}
          client-secret: ${AZURE_CLIENT_SECRET}
        redirect-uri-template: ${gpfd.redirect-uri-template}
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read

server:
  port: 8443
  forward-headers-strategy: native # not sure if needed
  shutdown: graceful
  servlet:
    session:
      cookie:
        secure: true
  ssl:
    key-store: classpath:gpfd-ssl-keystore.p12
    key-store-password: ${SSL-DEV-KEY-STORE-PASSWORD}
    key-store-type: PKCS12
    key-alias: gpfd-dev-ssl-key
    key-password: ${SSL-DEV-KEY-STORE-PASSWORD}


