logging:
  structured:
    format:
      console: "" # Disable ECS JSON locally for human-readable logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%X{traceId},%X{spanId}] --- [%15.15t] %-40.40logger{39} : %m%n%wEx"
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
        transaction: INFO
        web.client.RestTemplate: INFO


gpfd:
  url: http://localhost:8080
  redirect-uri-template: ${gpfd.url}/login/oauth2/code/gpfd-azure-dev
  security:
    cors:
      allowed-origin: http://localhost:8080

  datasource:
    read-only:
      url: jdbc:oracle:thin:@oracle-local:1521/FREEPDB1
      username: GPFD
      password: ${ORACLE_DB_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver
    write:
      url: jdbc:oracle:thin:@oracle-local:1521/FREEPDB1
      username: GPFD
      password: ${ORACLE_DB_PASSWORD}
      driver-class-name: oracle.jdbc.OracleDriver

spring:
  cloud:
    azure:
      active-directory:
        enabled: false
        profile:
          tenant-id: AZURE_TENANT_ID
        credential:
          client-id: AZURE_CLIENT_ID
          client-secret: AZURE_CLIENT_SECRET
        redirect-uri-template: ${gpfd.redirect-uri-template}
        authorization-clients:
          graph:
            scopes:
              - https://graph.microsoft.com/User.Read

  datasource:
    url: jdbc:oracle:thin:@oracle-local:1521/FREEPDB1
    username: GPFD
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: GPFD
    url: jdbc:oracle:thin:@oracle-local:1521/FREEPDB1
    user: GPFD
    password: ${ORACLE_DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none
    generate-ddl: false