logging:
  level:
    root: INFO
    org:
      springframework:
        security: INFO
        jdbc:
          core:
            JdbcTemplate: INFO
            StatementCreatorUtils: INFO
        transaction: INFO
        web: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /swagger.yml

spring:
  mvc:
    async:
      request-timeout: 3600000
  flyway:
    schemas: glad
    create-schemas: true
    locations: classpath:flyway/migration/schema
    url: ${gpfd.datasource.tracking.jdbcUrl}
    user: ${gpfd.datasource.tracking.username}
    password: ${gpfd.datasource.tracking.password}

gpfd:
  s3:
    # If this is true, the environment will need to be deployed with appropriate config and permission for accessing an S3 bucket.
    has-s3-access: false
  csv-generation:
    buffer-flush-frequency: 5000

  datasource:
    tracking:
      # Default connection details for local dev, overridden in other envs
      driver-class-name: org.postgresql.Driver
      jdbcUrl: jdbc:postgresql://${RDS_DB_HOST:localhost}:5432/glad
      username: user
      password: dev