INSERT INTO GPFD.REPORT_TRACKING(ID, REPORT_NAME, REPORT_URL, CREATION_TIME, MAPPING_ID, REPORT_GENERATED_BY)
VALUES (GPFD_TRACKING_TABLE_SEQUENCE.NEXTVAL, 'Initial Test Report Name', 'https://www.some-url.com',
        '2024-03-18T12:10:11.814596',
        2, 'Bill Evans');