DROP USER GPFD CASCADE;

CREATE USER GPFD
  IDENTIFIED BY <password>
  HTTP DIGEST DISABLE
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

-- 6 System Privileges for GPFD 
GRANT CREATE PROCEDURE TO GPFD;
GRANT CREATE SEQUENCE TO GPFD;
GRANT CREATE SESSION TO GPFD;
GRANT CREATE TABLE TO GPFD;
GRANT CREATE VIEW TO GPFD;
GRANT SELECT ANY TABLE TO GPFD;

-- 1 Tablespace Quota for GPFD 
ALTER USER GPFD QUOTA UNLIMITED ON USERS;

-- 1 Object Privilege for GPFD 
GRANT EXECUTE ON FIN_BATCH.UTIL TO GPFD;