CREATE SCHEMA IF NOT EXISTS GPFD;

CREATE SEQUENCE IF NOT EXISTS GPFD_TRACKING_TABLE_SEQUENCE
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS GPFD.REPORT_TRACKING
(
    ID                  INTEGER      NOT NULL,
    REPORT_NAME         VARCHAR(80)  NOT NULL,
    REPORT_URL          VARCHAR(500) NOT NULL,
    CREATION_TIME       TIMESTAMP    NOT NULL,
    MAPPING_ID          INTEGER      NOT NULL,
    REPORT_GENERATED_BY VARCHAR(500) NOT NULL,
    CONSTRAINT pk_report_tracking_id PRIMARY KEY (id)
);



--  CREATE TABLE "GPFD"."CSV_TO_SQL_MAPPING_TABLE"
--   (	"ID" NUMBER(*,0),
--	"REPORT_NAME" VARCHAR2(200 BYTE),
--	"SQL_QUERY" VARCHAR2(4000 BYTE),
--	"BASE_URL" VARCHAR2(450 BYTE),
--	"REPORT_OWNER" VARCHAR2(100 BYTE),
--	"REPORT_CREATOR" VARCHAR2(100 BYTE),
--	"REPORT_DESCRIPTION" VARCHAR2(400 BYTE),
--	"EXCEL_REPORT" VARCHAR2(200 BYTE),
--	"EXCEL_SHEET_NUM" NUMBER,
--	"CSV_NAME" VARCHAR2(200 BYTE),
--	"OWNER_EMAIL" VARCHAR2(300 BYTE)
--   ) SEGMENT CREATION IMMEDIATE
--  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
-- NOCOMPRESS LOGGING
--  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
--  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
--  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
--  TABLESPACE "USERS" ;
--  GRANT SELECT ON "GPFD"."CSV_TO_SQL_MAPPING_TABLE" TO "ANY_REPORT";