-- Create GPFD schema
CREATE SCHEMA IF NOT EXISTS GPFD;

-- Create GPFD tables
CREATE TABLE IF NOT EXISTS GPFD.REPORT_OUTPUT_TYPES (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    EXTENSION VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS GPFD.REPORTS (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME VARCHAR(150),
    TEMPLATE_SECURE_DOCUMENT_ID VARCHAR(300),
    REPORT_CREATION_DATE DATE,
    LAST_DATABASE_REFRESH_DATETIME TIMESTAMP,
    DESCRIPTION VARCHAR(4000),
    NUM_DAYS_TO_KEEP INT,
    REPORT_OUTPUT_TYPE UUID,
    REPORT_OWNER_ID UUID,
    REPORT_OWNER_NAME VARCHAR(150),
    REPORT_OWNER_EMAIL VARCHAR(150),
    FILE_NAME VARCHAR(150),
    ACTIVE CHAR(1),
    CONSTRAINT fk_report_output_types FOREIGN KEY (REPORT_OUTPUT_TYPE) REFERENCES GPFD.REPORT_OUTPUT_TYPES(ID)
);

CREATE TABLE IF NOT EXISTS GPFD.REPORT_QUERIES (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    REPORT_ID UUID,
    QUERY VARCHAR(4000),
    TAB_NAME VARCHAR(100),
    "INDEX" VARCHAR(100),
    CONSTRAINT fk_report_queries_report FOREIGN KEY (REPORT_ID) REFERENCES GPFD.REPORTS(ID)
);

CREATE TABLE IF NOT EXISTS GPFD.FIELD_ATTRIBUTES (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    REPORT_QUERY_ID UUID,
    SOURCE_NAME VARCHAR(100) NOT NULL,
    MAPPED_NAME VARCHAR(100) NOT NULL,
    FORMAT VARCHAR(100),
    FORMAT_TYPE VARCHAR(100) NOT NULL,
    COLUMN_WIDTH DECIMAL(6,2) NOT NULL,
    COLUMN_ORDER DECIMAL(6,0) DEFAULT 0,
    CONSTRAINT fk_field_attributes_query FOREIGN KEY (REPORT_QUERY_ID) REFERENCES GPFD.REPORT_QUERIES(ID)
);

CREATE TABLE IF NOT EXISTS GPFD.REPORT_GROUPS (
    REPORT_ID UUID,
    GROUP_ID UUID,
    CONSTRAINT fk_report_groups_report FOREIGN KEY (REPORT_ID) REFERENCES GPFD.REPORTS(ID)
);

CREATE TABLE IF NOT EXISTS GPFD.REPORTS_TRACKING (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    REPORT_ID UUID NOT NULL,
    CREATION_DATE DATE,
    REPORT_DOWNLOADED_BY VARCHAR(150),
    REPORT_CREATOR VARCHAR(150) NOT NULL,
    REPORT_OWNER VARCHAR(150) NOT NULL,
    REPORT_OUTPUT_TYPE VARCHAR(150) NOT NULL,
    TEMPLATE_URL VARCHAR(300) NOT NULL,
    REPORT_URL VARCHAR(300) NOT NULL,
    CONSTRAINT fk_reports_tracking_report FOREIGN KEY (REPORT_ID) REFERENCES GPFD.REPORTS(ID)
);

CREATE TABLE IF NOT EXISTS GPFD.REPORT_TRACKING (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    REPORT_NAME VARCHAR(80) NOT NULL,
    REPORT_URL VARCHAR(500) NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL,
    MAPPING_ID UUID NOT NULL,
    REPORT_GENERATED_BY VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS GPFD.CSV_TO_SQL_MAPPING_TABLE (
    ID UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    REPORT_NAME VARCHAR(500) NOT NULL,
    SQL_QUERY VARCHAR(500) NOT NULL,
    BASE_URL VARCHAR(500) NOT NULL,
    REPORT_OWNER VARCHAR(500) NOT NULL,
    REPORT_CREATOR VARCHAR(500) NOT NULL,
    REPORT_DESCRIPTION VARCHAR(500) NOT NULL,
    EXCEL_REPORT VARCHAR(500) NOT NULL
);

-- Create sequence only if it doesn't exist
CREATE SEQUENCE IF NOT EXISTS GPFD.GPFD_TRACKING_TABLE_SEQUENCE START WITH 1 INCREMENT BY 1;

-- Create ANY_REPORT schema for test data
CREATE SCHEMA IF NOT EXISTS ANY_REPORT;

CREATE TABLE IF NOT EXISTS ANY_REPORT.FISH_AND_CHIP_SALE_LEDGER (
    SALES_PERSON_NAME VARCHAR(100),
    SALE_DATE DATE,
    FISH_QUANTITY INT,
    CHIP_QUANTITY INT,
    TOTAL_COST DECIMAL(10,2)
);

CREATE TABLE IF NOT EXISTS ANY_REPORT.MARSHMALLOW_DENSITY_SUMMARY_VIEW (
    LOCATION VARCHAR(100),
    MARSHMALLOW_TYPE VARCHAR(100),
    AVERAGE_DENSITY DECIMAL(10,2),
    SAMPLE_COUNT INT
);
