openapi: 3.0.0
info:
  title: PayForLegalAid API
  version: 1.0.0
  description: API for accessing financial reports related to legal aid payments.
  contact:
    name: Ministry of Justice

paths:
  /reports:
    get:
      summary: List All Available Reports
      description: Retrieves a list of all available reports, including each report's ID, name, and metadata.
      responses:
        '200':
          description: A JSON array containing metadata for each report.
          content:
            application/json:
              schema:
                type: object
                properties:
                  reportList:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 1
                        reportName:
                          type: string
                          example: "Invoice_analysis"
                        excelReport:
                          type: string
                          example: "invoice_analysis"
                        csvName:
                          type: string
                          example: "import-analysis"
                        excelSheetNum:
                          type: integer
                          example: 2
                        sqlQuery:
                          type: string
                          example: "SELECT * FROM FOO"
                        baseUrl:
                          type: string
                          example: "/General%20Tools/invoice%20analysis.xlsb"
                        reportOwner:
                          type: string
                          example: "Mr Bean"
                        reportCreator:
                          type: string
                          example: "Mr Bean"
                        description:
                          type: string
                          example: "Summary of invoices by source system"
                        ownerEmail:
                          type: string
                          example: "owneremail@email.com"
        '401':
          description: Unauthorized. A valid OAuth2 token is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access. OAuth2 token required."
        '500':
          description: Database read error or unknown server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "DatabaseReadException: Unable to fetch report list."

  /report/{id}:
    get:
      summary: Retrieve Report Metadata by ID
      description: Fetches metadata for a specific report using the provided report ID. This includes the report name, ID, and download URL.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The unique ID of the requested report.
      responses:
        '200':
          description: JSON object with metadata for the specified report.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  reportName:
                    type: string
                    example: "Invoice_analysis-analysis"
                  reportDownloadUrl:
                    type: string
                    format: uri
                    example: "https://<service_destination>/csv/1"
        '401':
          description: Unauthorized. A valid OAuth2 token is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access. OAuth2 token required."
        '404':
          description: Report ID not found in the database.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "IndexOutOfBoundsException: Report ID not found."
        '500':
          description: Unknown server error during report fetch.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "An error occurred while fetching report metadata."

  /csv/{id}:
    get:
      summary: Download Report as CSV Stream
      description: Provides a CSV data stream for a specified report ID. This can trigger a file download when accessed via a browser.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
          description: The unique ID of the requested report.
      responses:
        '200':
          description: A CSV data stream of the report.
          content:
            text/csv:
              schema:
                type: string
                format: binary
                example: |
                  "date","amount","description"
                  "2023-01-01","1000","Legal Aid Case Payment"
        '401':
          description: Unauthorized. A valid OAuth2 token is required.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Unauthorized access. OAuth2 token required."
        '404':
          description: Report ID not found in the tracking system.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "ReportIdNotFoundException: Report ID 1 not found."
        '500':
          description: Server error encountered while streaming CSV data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "CsvStreamException: Failed to generate CSV stream."