name: Snyk Scan

runs:
  using: 'composite'

  steps:
    - name: Setup Snyk CLI
      uses: snyk/actions/setup@master

    - name: Run Snyk scan
      run: snyk test -d --all-projects --severity-threshold=high --sarif-file-output=snyk.sarif
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
      shell: bash

    - name: Replace security-severity undefined for license-related findings
      run: |
        sed -i "s/\"security-severity\": \"undefined\"/\"security-severity\": \"0\"/g" snyk.sarif
        sed -i "s/\"security-severity\": \"null\"/\"security-severity\": \"0\"/g" snyk.sarif
      shell: bash

    - name: Upload Snyk results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
