name: Build and run tests

runs:
  using: 'composite'
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: maven-settings
      uses: s4u/maven-settings-action@v2
      with:
          servers: '[{"id": "github", "username": "${USERNAME}", "password": "${PASSWORD}"}]'
          githubServer: false
    - name: Run Tests with Maven
      run: mvn test
      env:
        USERNAME: ${{ env.USERNAME }}
        PASSWORD: ${{ env.PASSWORD }}

      shell:
        bash


    - name: Run tests
      run: mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash