name: Build and run tests
description: Build the application and run tests in a local environment

runs:
  using: 'composite'
  steps:

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'

    - name: Build OpenAPI dependency
      uses: './.github/checkout-build-openapi'
      env:
        SOCKET_KEY: ${{ env.SOCKET_KEY }}

    - name: Run tests
      run: |
#        TODO put back in!
#        mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash

    - name: Generate JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      run: mvn jacoco:report
      env:
        SPRING_PROFILES_ACTIVE: test
      shell: bash

    - name: Upload JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: jacoco-report-${{ github.job }}-${{ github.run_attempt }}
        path: target/site/jacoco
