name: Build and run tests

runs:
  using: 'composite'
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-swagger
        path: spec
        ssh-key: ${{ env.SOCKET_KEY }}

    - name: Build dependency
      run: |
        cd spec
        mvn clean install -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
      shell:
        bash

    - name: Run tests
      run: |
        mvn -B clean test -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash
