name: Build and run tests

runs:
  using: 'composite'
  steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        server-id: github
        server-username: ${{ secrets.USERNAME }}
        server-password: ${{ secrets.PASSWORD }}
        repository-id: github
        repository-url: https://maven.pkg.github.com/ministryofjustice/payforlegalaid-openapi

#    - name: Set values in settings.xml
#      uses: s4u/maven-settings-action@v3.1.0
#      with:
#        servers: |
#          [{
#            "id": "github",
#            "username": "something invalid",
#            "password": "another invalid thing"
#          }]

    - name: Run tests
      run: mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash