name: Build and run tests
description: Build the application and run tests in a local environment

runs:
  using: 'composite'
  steps:

    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup Java
      uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'

    - name: Setup Maven
      uses: './.github/setup-maven'
      with:
        github-username: ${{ inputs.github-username }}
        github-token: ${{ inputs.github-token }}

    - name: Run unit tests
      run: |
        mvn -ntp -B clean test -Dtest='!*RunCucumberTest'
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash

    - name: Generate JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      run: mvn jacoco:report
      env:
        SPRING_PROFILES_ACTIVE: test
      shell: bash

    - name: Upload JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: jacoco-report-${{ github.job }}-${{ github.run_attempt }}
        path: target/site/jacoco
