name: Build and run tests
description: Build the application and run tests in a local environment

inputs:
  github-username:
    required: true
    description: GitHub username
  github-token:
    required: true
    description: GitHub token

runs:
  using: 'composite'
  steps:

    - name: Setup Java
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'

    - name: Run unit tests
      env:
        SPRING_PROFILES_ACTIVE: test
        GITHUB_USERNAME: ${{ inputs.github-username }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell:
        bash
      run: |
        mvn -s .github/settings.xml -ntp -B clean test -Dtest='!*RunCucumberTest'

    - name: Generate JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      env:
        SPRING_PROFILES_ACTIVE: test
        GITHUB_USERNAME: ${{ inputs.github-username }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      shell: bash
      run: mvn -s .github/settings.xml jacoco:report

    - name: Upload JaCoCo Report (development only)
      if: ${{ github.environment == 'development' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: jacoco-report-${{ github.job }}-${{ github.run_attempt }}
        path: target/site/jacoco
