name: Get Data Registry Details

outputs:
  data_registry:
    description: "Registry details for the data ECR"
    value: ${{ steps.set-data-registry.outputs.data_registry }}

runs:
  using: 'composite'

  steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Login to aws for data ecr
    uses: './.github/login-to-aws'
    env:
      ROLE: ${{ env.ROLE }}
      AWS_REGION: ${{ env.AWS_REGION }}

  - name: Login to data container repository
    uses: aws-actions/amazon-ecr-login@v2
    id: login-ecr-data

  - name: Set data registry output
    id: set-data-registry
    run: |
      echo "data_registry=${{ steps.login-ecr-data.outputs.registry }}" >> "$GITHUB_OUTPUT"
    shell: bash