name: Build and push docker image

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4

    # Login to container repository
    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    # Build and push a Docker image to the container repository
    - run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ env.REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      shell: bash

