name: Build and push docker image

runs:
  using: 'composite'

  steps:
    - uses: actions/checkout@v4

    # Build and push a Docker image to the container repository
    - run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        echo "barfoo action"
        echo ${{ env.REGISTRY }}
      env:
        REGISTRY: ${{ env.REGISTRY }}
        REPOSITORY: ${{ env.REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      shell: bash

