name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-tests
        path: testCode

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'

    - name: Checkout source code repo
      uses: actions/checkout@v4
      with:
        path: sourceCode

    - name: Build source code
      run: |
        cd sourceCode
        mvn -B -DskipTests clean install -s .github/settings.xml
      shell:
        bash

    - name: Run tests
      run: |
        cd testCode
        mvn -B clean test -s .github/settings.xml

      shell:
        bash
