name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-tests
        path: testCode

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Checkout and build openapi
      uses: './.github/checkout-build-openapi'
      id: get_openapi_version
      with:
        subfolder: 'testCode'

    - name: Checkout source code repo
      uses: actions/checkout@v4
      with:
        path: sourceCode

    - name: Test S3
      run: |
        aws s3 sync s3://${{ env.S3_BUCKET }}/templates sourceCode/src/main/resources
      shell:
        bash

    - name: Check folder
      run: |
        ls sourceCode/src/main/resources
      shell:
        bash

    - name: Build source code
#     Uses cached dependencies from build-and-test action
      run: |
        cd sourceCode
        mvn -B install -DskipTests
      shell:
        bash

    - name: Run tests
      env:
        # todo ??????
        TESTS_TO_DISABLE: "get_excel_report"
      run: |
        cd testCode
        mvn -B clean test
      shell:
        bash
