name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Assume role in Cloud Platform
      uses: './.github/login-to-aws'
      env:
        ROLE: ${{ env.ROLE }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Setup Java
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        distribution: 'corretto'
        java-version: '25'
        cache: 'maven'

    - name: Checkout and build openapi
      uses: './.github/checkout-build-openapi'
      id: get_openapi_version

    - name: Get necessary templates from S3
      env:
        S3_BUCKET: ${{ env.S3_BUCKET }}
      run: |
        aws s3 sync s3://${S3_BUCKET}/templates src/main/resources
      shell: bash

#    ** Debug only - prints a list of resources available in /src/main/resources **
#    **i.e. templates, changelog files, application-*.yml files, etc.**

#    - name: List downloaded templates
#      run: |
#        find src/main/resources -type f | sort
#      shell: bash

    - name: Resolve application version
      run: |
        APP_VERSION=$(mvn help:evaluate \
          -Dexpression=project.version \
          -q \
          -DforceStdout)

        if [[ -z "${APP_VERSION// }" ]]; then
          echo "ERROR: Failed to resolve APP_VERSION"
          exit 1
        fi

        echo "APP_VERSION=${APP_VERSION}" >> "$GITHUB_ENV"
        echo "Using APP_VERSION=${APP_VERSION}"
      shell: bash

    - name: Run acceptance tests
      run: |
        mvn -B -ntp test \
          -Dtest=RunCucumberTest \
          -Dcucumber.filter.tags="not @performance"
      env:
        SPRING_PROFILES_ACTIVE: testat
      shell: bash

    - name: Publish cucumber results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-reports
        path: |
          **/cucumber-report.html