name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-tests
        path: testCode

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Get openapi version from pom
      id: get_openapi_version
      run: |
        cd testCode
        VERSION=$(mvn help:evaluate -Dexpression=payforlegalaid-openapi.version -q -DforceStdout)
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Checkout source code repo
      uses: actions/checkout@v4
      with:
        path: sourceCode

    - name: Build source code
      run: |
        cd sourceCode
        mvn -B -DskipTests clean install -Dpayforlegalaid-openapi.version=${{ steps.get_openapi_version.outputs.version }}
      shell:
        bash

    - name: Run tests
      run: |
        cd testCode
        mvn -B clean test -s -Dpayforlegalaid-openapi.version=${{ steps.get_openapi_version.outputs.version }}

      shell:
        bash
