name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-tests
        path: testCode

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Checkout and build openapi
      uses: './.github/checkout-build-openapi'
      id: get_openapi_version
      with:
        property-name: 'payforlegalaid-openapi.version'

    - name: Checkout source code repo
      uses: actions/checkout@v4
      with:
        path: sourceCode

    - name: Build source code
      run: |
        cd sourceCode
        mvn -B -DskipTests clean install
#        -Dpayforlegalaid-openapi.version=${{ steps.get_openapi_version.outputs.version }}
      shell:
        bash

    - name: Run tests
      env:
        TESTS_TO_DISABLE: "get_excel_report"
      run: |
        cd testCode
        mvn -B clean test
      shell:
        bash
