name: Build and test

runs:
  using: 'composite'

  steps:
    - name: Assume role in Cloud Platform
      uses: './.github/login-to-aws'
      env:
        ROLE: ${{ env.ROLE }}
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Checkout GitHub repository
      uses: actions/checkout@v4
      with:
        repository: ministryofjustice/payforlegalaid-tests
        path: testCode

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
        cache: 'maven'

    - name: Checkout and build openapi
      uses: './.github/checkout-build-openapi'
      id: get_openapi_version
      with:
        subfolder: 'testCode'

    - name: Checkout source code repo
      uses: actions/checkout@v4
      with:
        path: sourceCode

    - name: Get necessary templates from S3
#      If in future we add reports without adding an AT, we could filter this to just ones needed in a test
      run: |
        aws s3 sync s3://${{ env.S3_BUCKET }}/templates sourceCode/src/main/resources
      shell:
        bash

    - name: Build source code
#     Uses cached dependencies from build-and-test action
      run: |
        cd sourceCode
        mvn -B install -DskipTests
      shell:
        bash

    - name: Run tests
      run: |
        cd testCode
        mvn -B clean test
      shell:
        bash
