INSERT INTO ANY_REPORT.V_CIS_TO_CCMS_INVOICE_SUMMARY(DATE_AUTHORISED_CIS, THE_SYSTEM, CIS_VALUE, CCMS_VALUE)
VALUES ('Auth Date', 'Test System', 'Test Value', 'Test Value');

INSERT INTO ANY_REPORT.V_CIS_TO_CCMS_INVOICE_DEFINED_PAYMENT_GROUPS(DATE_AUTHORISED_CIS, THE_SYSTEM, CIS_VALUE, CCMS_VALUE)
VALUES ('Auth Date', 'Test System', 'Test Value', 'Test Value');