{
 "title": "LAA Get Payment & Finance Data Prod Dashboard",
 "tags": [
  "api",
  "LAA",
  "LAA Get Payments & Finance Data",
  "GPFD",
  "Get Legal Aid Data",
  "GLAD"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Api Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods Info",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='${NAMESPACE}'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Running',pod=~'.*deployment.*'} + 0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Pending',pod=~'.*deployment.*'} + 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Failed',pod=~'.*deployment.*'} + 0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Unauthorised Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 2, "y": 1 },
   "targets": [
    {
     "expr": "sum by(application) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}', status='401'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per Pod Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}',application='gpfd-api-app', status='200'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api Endpoints Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}', uri!~'.*actuator.*|.*swagger.*|.*reports*|.*csv.*', status='200'}[$__rate_interval])) ",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{namespace='${NAMESPACE}',application='gpfd-api-app', uri!~'.*actuator.*|.*swagger.*|.*reports*|.*csv.*', status='200'}[1m])) / sum by(uri) (rate(http_server_requests_seconds_count{namespace='${NAMESPACE}',application='gpfd-api-app', uri!~'.*actuator.*|.*swagger.*|.*reports*|.*csv.*', status='200'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(uri) (http_server_requests_seconds_max{namespace='${NAMESPACE}',application='gpfd-api-app', uri!~'.*actuator.*|.*swagger.*|.*reports*|.*csv.*', status='200'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DB Connection Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Max Survivor",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',application='gpfd-api-app', area='heap', id='Survivor Space', namespace='${NAMESPACE}'} / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Survivor Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 2, "y": 32 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',application='gpfd-api-app',area='heap',id='Survivor Space',}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Eden",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 8, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',application='gpfd-api-app',area='heap',id='Eden Space',}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Eden Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 32 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',application='gpfd-api-app',area='heap',id='Eden Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Tenured",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',application='gpfd-api-app',area='heap',id='Tenured Gen',} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Tenured Gen (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',application='gpfd-api-app',area='heap',id='Tenured Gen',} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}