name: Build and run tests

runs:
  using: 'composite'
  steps:

    # Run Tests
    - name: Run tests
      run: mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash
