name: Build and run tests

inputs:
  version:
    description: "Version of the environment"
    required: true
    default: "latest"

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    # Run Tests
    - name: Run tests
      run: mvn -B clean test
      env:
        SPRING_PROFILES_ACTIVE: test
      shell:
        bash

    # Build and package JAR
    - name: Build with Maven
      run: mvn -B -DskipTests clean package
      shell:
        bash
