{
 "title": "LAA GPFD Get Payment & Finance Data ${ENV_NAME} dashboard",
 "tags": [
  "api",
  "LAA",
  "LAA Get Payments & Finance Data",
  "GPFD",
  "Get Legal Aid Data",
  "GLAD"
 ],
 "time": { "from": "2026-07-08T04:10:36.246Z", "to": "2026-07-08T15:49:33.816Z" },
 "panels": [
  { "title": "Report Downloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Downloads",
   "type": "timeseries",
   "description": "Monitoring the database connection pool usage.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{namespace='${NAMESPACE}',uri=~\"/reports/(.*)/(file|excel|csv)\",status=\"200\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoint-wise Downloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(endpoint)(label_replace(label_replace(increase(http_server_requests_seconds_count{namespace='${NAMESPACE}',status=\"200\",uri=~\"/reports/.*/(csv|file|excel)\"}[$__rate_interval]),\"endpoint\", \"$1\", \"uri\", \"/reports/.*/(csv|file|excel)\"), \"endpoint\", \"S3\", \"endpoint\", \"file\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security Alert: Unauthorized Report Access",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(type)(label_replace(label_replace(increase(http_server_requests_seconds_count{namespace='${NAMESPACE}', status=\"403\", uri=~\"/reports/.*\"}[$__rate_interval]), \"type\", \"$1\", \"uri\", \".*/reports/.*(csv|file|excel)?\"), \"type\", \"S3\", \"type\", \"/reports/.*/file\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Requests Per Api Endpoints",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(uri) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}', uri!~'.*swagger.*|.*health.*', status='200'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database (PostgreSQL)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Current active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "db_tracking_connections_active{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "db_tracking_connections_max{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of open connections",
   "type": "timeseries",
   "description": "Amount of total open database connections",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 20 },
   "targets": [
    {
     "expr": "db_tracking_connections{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connection utilisation",
   "type": "timeseries",
   "description": "The % of connections we are actively utilising",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "100 * db_tracking_connections_utilisation_active{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total pool utilisation (%)",
   "type": "timeseries",
   "description": "Tracking the total utilisation of the database connection pool",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "100 * db_tracking_connections_utilisation_total_utilisation{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle connections",
   "type": "timeseries",
   "description": "Tracking the number of idle database connections",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "db_tracking_connections_idle{namespace='${NAMESPACE}'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions per day (commits)",
   "type": "timeseries",
   "description": "Tracking the rate of transactions the database deals with per day.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "increase(\n  db_tracking_transactions_commits{\n    namespace='${NAMESPACE}'\n  }[1d]\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks per day",
   "type": "timeseries",
   "description": "The rate of rollbacks we have had for transactions to our database",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "rate(db_tracking_transactions_rollbacks{namespace='${NAMESPACE}'}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% of Rollbacks to Transactions",
   "type": "timeseries",
   "description": "Tracking the rate of rollbacks compared to transactions",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "100 * rate(db_tracking_transactions_rollbacks{namespace='${NAMESPACE}'}[1d])rate(db_tracking_transactions_commits{namespace='${NAMESPACE}'}[1d]) + rate(db_tracking_transactions_rollbacks{namespace='${NAMESPACE}'}[1d]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections by pod",
   "type": "timeseries",
   "description": "Tracking the number of active connections per pod",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "targets": [
    {
     "expr": "sum by (pod) (db_tracking_connections_active{namespace='${NAMESPACE}'})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Requests Per Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 9, "y": 72 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(http_server_requests_seconds_count{namespace='${NAMESPACE}',status='200'}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "HTTP Code 403 including WAF check threshold",
   "type": "timeseries",
   "description": "HTTP Code 403 including WAF check threshold to display non-issue 403's as well as regular WAF checks which tend to occur every 8 hours or so",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace=\"${NAMESPACE}\", status=\"403\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code 4xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"${NAMESPACE}\",status=~\"4.*\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Code 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = '${NAMESPACE}',status=~\"5.*\"}[5m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "Average Response Time Per Uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(http_server_requests_seconds_sum{namespace='${NAMESPACE}', uri!~'.*swagger.*|.*health.*', status='200'}[1m])) / sum by(uri) (rate(http_server_requests_seconds_count{namespace='${NAMESPACE}', uri!~'.*swagger.*|.*health.*', status='200'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Response Time Per Uri",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by(uri) (http_server_requests_seconds_max{namespace='${NAMESPACE}', uri!~'.*swagger.*|.*health.*', status='200'}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Pods overview metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Pods Info",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_info{namespace='${NAMESPACE}',pod=~'.*gpfd.*'})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Running',pod=~'.*gpfd.*'} + 0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Pending',pod=~'.*gpfd.*'} + 0)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum({namespace='${NAMESPACE}',phase='Failed',pod=~'.*gpfd.*'} + 0)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 2, "y": 111 },
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='${NAMESPACE}'}[5m]))))",
     "legendFormat": "Average Bytes Received"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='${NAMESPACE}'}[5m]))))",
     "legendFormat": "Average Bytes Transmitted"
    }
   ]
  },
  {
   "title": "Resource quota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * kube_resourcequota{job=\"kube-state-metrics\", type=\"used\", namespace=\"${NAMESPACE}\"}\n/ ignoring(instance, job, type)\n(kube_resourcequota{job=\"kube-state-metrics\", type=\"hard\", namespace=\"${NAMESPACE}\"} > 0)",
     "legendFormat": "pods"
    }
   ]
  },
  {
   "title": "ECR Images count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 111 },
   "targets": [
    {
     "expr": "sum(aws_ecr_repository_image_count{repository_name=~'payforlegalaid/.*'}) by (repository_name)",
     "legendFormat": "ECR Image Count"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Percentage of container memory request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{image!='',namespace='${NAMESPACE}',pod=~\"gpfd.*\"}) by (container, pod)\n      /\n    sum(kube_pod_container_resource_requests{resource='memory', namespace='${NAMESPACE}',pod=~\"gpfd.*\"} > 0) by (container, pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Percentage of container memory limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(container_memory_working_set_bytes{image!=\"\", namespace='${NAMESPACE}', container_name!=\"gpfd.*\"}) by (container, pod)\n      /\n    sum(kube_pod_container_resource_requests{namespace='${NAMESPACE}', container_name!=\"gpfd.*\",resource=\"memory\"} > 0) by (container, pod)\n)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 122 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace='${NAMESPACE}', pod=~'gpfd.*'}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_max_usage_bytes{namespace=\"${NAMESPACE}\", pod=~'gpfd.*'}",
     "legendFormat": "{{pod}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 } },
  {
   "title": "Percentage of CPU request",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace='${NAMESPACE}', container_name!=\"gpfd.*\"}[5m])\n    ) by (pod, container_name, namespace)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace='${NAMESPACE}', container_name!='gpfd.*', resource='cpu'}\n    ) by (pod, container_name, namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percentage of container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "round(\n  100 *\n    sum(\n      rate(container_cpu_usage_seconds_total{namespace='${NAMESPACE}', container_name!=\"gpfd.*\"}[5m])\n    ) by (pod_name, container_name, namespace)\n      /\n    sum(\n      kube_pod_container_resource_limits{namespace='${NAMESPACE}', container_name!=\"gpfd.*\",resource='cpu'}\n    ) by (pod_name, container_name, namespace)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Instance",
   "type": "timeseries",
   "description": "Top 3 CPU Used Per Instance",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "topk(3, max by (pod, container)(rate(container_cpu_usage_seconds_total{image!='', namespace='${NAMESPACE}',pod=~\"gpfd.*\"}[$__rate_interval]))) / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Metrics: active threads & queue size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "sum(executor_active_threads{namespace=\"${NAMESPACE}\"})",
     "legendFormat": "Number of threads actively executing tasks"
    },
    {
     "expr": "sum(executor_pool_max_threads{namespace=\"${NAMESPACE}\"})",
     "legendFormat": "The maximum allowed number of threads in the pool"
    }
   ]
  },
  { "title": "JVM Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Max Survivor",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 0, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Survivor Space'} / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Survivor Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 2, "y": 151 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Survivor Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Eden",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 8, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Eden Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Eden Space (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 10, "y": 151 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Eden Space'}/1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Tenured",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 2, "x": 16, "y": 151 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_max_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Old Gen'} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Tenured Gen (MB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 151 },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace='${NAMESPACE}',area='heap',id='G1 Old Gen'} /1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 161 } },
  {
   "title": "Content Security Policy Violations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
   "targets": [
    {
     "expr": "sum(rate(csp_violations_total{namespace='${NAMESPACE}'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}