ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER GPFD IDENTIFIED BY password123
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

CREATE USER ANY_REPORT IDENTIFIED BY password123
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO GPFD;
GRANT CONNECT, RESOURCE TO ANY_REPORT;

-- GPFD needs cross-schema access to ANY_REPORT tables
GRANT CREATE ANY TABLE TO GPFD;
GRANT INSERT ANY TABLE TO GPFD;
GRANT SELECT ANY TABLE TO GPFD;
GRANT UPDATE ANY TABLE TO GPFD;
GRANT DELETE ANY TABLE TO GPFD;
GRANT CREATE ANY SEQUENCE TO GPFD;
GRANT SELECT ANY SEQUENCE TO GPFD;
GRANT CREATE ANY INDEX TO GPFD;