#!/bin/bash
set -e

: "${ORACLE_DB_PASSWORD:?ERROR: ORACLE_DB_PASSWORD is not set or empty. Please create .env file and set password}"

sqlplus -s / as sysdba << EOF
WHENEVER SQLERROR EXIT FAILURE ROLLBACK

ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
    -- GPFD user
    BEGIN
        EXECUTE IMMEDIATE 'CREATE USER GPFD IDENTIFIED BY "${ORACLE_DB_PASSWORD}"
            DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1920 THEN  -- ORA-01920: user name already exists
                DBMS_OUTPUT.PUT_LINE('User GPFD already exists, skipping creation');
            ELSE
                RAISE;  -- anything else is a real failure — abort
            END IF;
    END;

    -- ANY_REPORT user
    BEGIN
        EXECUTE IMMEDIATE 'CREATE USER ANY_REPORT IDENTIFIED BY "${ORACLE_DB_PASSWORD}"
            DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -1920 THEN
                DBMS_OUTPUT.PUT_LINE('User ANY_REPORT already exists, skipping creation');
            ELSE
                RAISE;
            END IF;
    END;

    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO GPFD';
    EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE TO ANY_REPORT';
    EXECUTE IMMEDIATE 'GRANT CREATE ANY TABLE  TO GPFD';
    EXECUTE IMMEDIATE 'GRANT INSERT ANY TABLE  TO GPFD';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY TABLE  TO GPFD';
    EXECUTE IMMEDIATE 'GRANT UPDATE ANY TABLE  TO GPFD';
    EXECUTE IMMEDIATE 'GRANT DELETE ANY TABLE  TO GPFD';
    EXECUTE IMMEDIATE 'GRANT CREATE ANY SEQUENCE TO GPFD';
    EXECUTE IMMEDIATE 'GRANT SELECT ANY SEQUENCE TO GPFD';
    EXECUTE IMMEDIATE 'GRANT CREATE ANY INDEX  TO GPFD';

EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;
/

EXIT;
EOF