#!/bin/bash
set -e

sqlplus -s / as sysdba << EOF
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER GPFD IDENTIFIED BY ${ORACLE_DB_PASSWORD}
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

CREATE USER ANY_REPORT IDENTIFIED BY ${ORACLE_DB_PASSWORD}
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO GPFD;
GRANT CONNECT, RESOURCE TO ANY_REPORT;

GRANT CREATE ANY TABLE TO GPFD;
GRANT INSERT ANY TABLE TO GPFD;
GRANT SELECT ANY TABLE TO GPFD;
GRANT UPDATE ANY TABLE TO GPFD;
GRANT DELETE ANY TABLE TO GPFD;
GRANT CREATE ANY SEQUENCE TO GPFD;
GRANT SELECT ANY SEQUENCE TO GPFD;
GRANT CREATE ANY INDEX TO GPFD;

EXIT;
EOF