name: Reusable checkout and build workflow
on:
  workflow_call:

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      # Checkout GitHub repository
      - uses: actions/checkout@v4

      # Setup Javax
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'