name: Test Invalid Dispatch

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      deploy_scope: chris1234