name: Deploy to Test Environment

on:
  push:
    branches:
      - 'test-*'


concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-deploy-to-testable:
    environment: development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Assume role in Cloud Platform
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.DEV_TEST_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.DEV_TEST_ECR_REGION }}

      - name: Login to container repository
        uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr
        with:
          role-to-assume: ${{ secrets.DEV_TEST_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.DEV_TEST_ECR_REGION }}

      - name: Authenticate with Cloud Platform and Deploy
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE_DEV }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER_DEV }}
        run: |
          echo "${{ secrets.KUBE_CERT_DEV }}" > ca.crt
          kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN_DEV }}
          kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
          kubectl config use-context ${KUBE_CLUSTER}

      - name: Checkout GitHub repository
        uses: actions/checkout@v4
        with:
          repository: ministryofjustice/payforlegalaid-tests
          ref: faeture/test-foo
          path: testCode

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Build docker-test
        run: |
          cd testCode
           docker build \
            --secret id=maven_username,env=USERNAME \
            --secret id=maven_password,env=PASSWORD \
            -t $REGISTRY/$REPOSITORY:gpfd-tests-$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:gpfd-tests-$IMAGE_TAG
        shell: bash
        env:
          USERNAME: ${{ secrets.OPENAPI_PACKAGE_USER }}
          PASSWORD: ${{ secrets.OPENAPI_PACKAGE_PASSWORD }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.TEST_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Set TEST_IMAGE environment variable
        run: |
          echo "TEST_IMAGE=$REGISTRY/$REPOSITORY:gpfd-tests-$IMAGE_TAG" >> $GITHUB_ENV
        shell: bash
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.DEV_TEST_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      - name: Update pod.yaml with test image
        run: |
          sed -i "s|\${TEST_IMAGE}|${TEST_IMAGE}|g" deployment/pod.yaml
          cat deployment/pod.yaml
        shell: bash

      - name: Build source code
        run: |
          ls -alp
          kubectl -n ${KUBE_NAMESPACE} create -f deployment/pod.yaml
        shell: bash
