name: pipeline test
'on': workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      # Checkout GitHub repository
      - uses: actions/checkout@v3

      # Setup Javax
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Run Tests
      - name: Run tests
        run: mvn -B clean test
        env:
          SPRING_PROFILES_ACTIVE: test
