name: pipeline test
'on': workflow_dispatch
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
          # Run Tests
      - name: Run tests
        run: mvn -B clean test
        env:
          SPRING_PROFILES_ACTIVE: test
