name: Rob's to the dev env fairy tail

on:
  workflow_dispatch:
  push:


jobs:
  feature_branch:

    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout
    steps:
      # Checkout GitHub repository
      - uses: actions/checkout@v3

      # Setup Javax
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Assume role in Cloud Platform
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}


      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr

      - name: Set Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=dev" >> $GITHUB_ENV
