name: Rob's to the dev env fairy tail

on:
  workflow_dispatch:
  push:


jobs:
  feature_branch:

    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      # Checkout GitHub repository
      - uses: actions/checkout@v4

      - name: Group of log lines
        run: |
          echo [FOOBAR] showing my credentials: ${{ secrets.ECR_ROLE_TO_ASSUME }}


      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}
      - uses: aws-actions/amazon-ecr-login@v2
        id: login-ecr

      - name: Set Spring profile
        run: echo "SPRING_PROFILES_ACTIVE=dev" >> $GITHUB_ENV

      # Setup Javax
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      # Build and package JAR
      - name: Build with Maven
        run: mvn -B -DskipTests clean package


      - run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}

      # Generate Kubernetes files from the deployments/dev/*.yml files
      - env:
          IMAGE_TAG: ${{ github.sha }} # Tags ECR image with commit sha
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          NAMESPACE: ${{ secrets.KUBE_NAMESPACE_DEV }}
        run: |
          echo $NAMESPACE
          cat deployments/dev/deployment.tpl | envsubst > deployments/dev/deployment.yml
          cat deployments/dev/ingress.tpl | envsubst > deployments/dev/ingress.yml
          cat deployments/dev/service.tpl | envsubst > deployments/dev/service.yml

      - run: |
          echo "${{ secrets.KUBE_CERT_DEV }}" > ca.crt]
          echo "${{ secrets.KUBE_CLUSTER_DEV }}" 
          kubectl config set-cluster ${{ secrets.KUBE_CLUSTER_DEV }} --certificate-authority=./ca.crt --server=https://${{ secrets.KUBE_CLUSTER_DEV }}
        env:
          KUBE_NAMESPACE: ${{ secrets.KUBE_NAMESPACE_DEV }}
          KUBE_CLUSTER: ${{ secrets.KUBE_CLUSTER_DEV }}
      
