name: Run Spotbugs

on:
  workflow_dispatch:

jobs:
  spotbugs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # This is required for uploading SARIF to Code Scanning
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run SpotBugs security scan
        uses: ./.github/spotbugs-scan
        with:
          github-username: ${{ secrets.GITHUB_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
