name: Run Spotbugs

on:
  workflow_dispatch:

jobs:
  spotbugs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # This is required for uploading SARIF to Code Scanning
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run SpotBugs security scan
        uses: ./.github/spotbugs-scan
        with:
          github-username: ${{ secrets.GITHUB_USERNAME }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
