name: Run Spotbugs

on:
  workflow_dispatch:

jobs:
  spotbugs:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # This is required for uploading SARIF to Code Scanning
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build OpenAPI dependency
        uses: './.github/checkout-build-openapi'
        env:
          SOCKET_KEY: ${{ env.SOCKET_KEY }}

      - name: Run SpotBugs security scan
        uses: ./.github/spotbugs-scan
