name: Scan docker image

on:
  workflow_dispatch:
  schedule:
    # Run at 7:30AM UTC every day
    - cron:  '30 07 * * *'

jobs:
  scan-docker-image:
      permissions:
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

      name: Scan docker image
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

        - name: Setup Java
          uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
          with:
            distribution: 'corretto'
            java-version: '25'

        - name: Build with Maven
          env:
            GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          shell:
            bash
          run: mvn -s .github/settings.xml -B -ntp -DskipTests clean package

        - name: Debug Docker info
          run: |
            docker info
            ls -al

        - name: Build docker image
          run: |
            docker build \
              --no-cache \
              --tag payforlegalaid:scan \
              --file Dockerfile .

        - name: Scan docker image using Snyk
          continue-on-error: true
          uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            image: payforlegalaid:scan
            args: --file=Dockerfile --sarif-file-output=snyk.sarif

        - name: Monitor docker image using Snyk
          uses: snyk/actions/docker@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          with:
            command: monitor
            image: payforlegalaid:scan
            args: --file=Dockerfile

        - name: Replace security-severity undefined for license-related findings
          # See https://github.com/github/codeql-action/issues/2187 for details
          run: |
            sed -i "s/\"security-severity\": \"undefined\"/\"security-severity\": \"0\"/g" snyk.sarif
            sed -i "s/\"security-severity\": \"null\"/\"security-severity\": \"0\"/g" snyk.sarif

        - name: Upload result to GitHub Code Scanning
          uses: github/codeql-action/upload-sarif@e0647621c2984b5ed2f768cb892365bf2a616ad1 # v4.37.2
          with:
            sarif_file: snyk.sarif
