name: Workflow Using Composite Action

on: [push]

jobs:
  setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use composite action
        uses: ./github/actions/my-composite-action
        with:
          version: '2.0'