name: OWASP ZAP UAT Scan

on:
  workflow_dispatch:
  pull_request:

  schedule:
    # Every weekday at 2am UTC
    - cron: '0 2 * * 1-5'

jobs:
  zap_scan:
    name: Run OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest

    continue-on-error: true

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@de8ad967d3548d44ef623df22cf95c3b0baf8b25 # v0.15.0
        with:
          target: 'https://uat-laa-get-payments-finance-data.cloud-platform.service.justice.gov.uk/'
          cmd_options: '-a'

      # Example external upload placeholder
      - name: Upload report to external storage
        if: always()
        run: |
          echo "Upload report_html.html to approved storage location"